### ISSUE TITLE
启动主题，显示错误Class 'Widget\Contents\Page\Rows' not found

### ISSUE THREAD

**Issue by magickzl** [17px/typecho-theme-shanhai#2]
由 [Typecho](http://typecho.org/) 强力驱动, 版本 1.2 (19.05.09)

启动主题，显示错误Class 'Widget\Contents\Page\Rows' not found

**Comment by 17px** [comment]
> 由 [Typecho](http://typecho.org/) 强力驱动, 版本 1.2 (19.05.09)
> 
> 启动主题，显示错误Class 'Widget\Contents\Page\Rows' not found

麻烦请试一下1.21+版本

**Comment by magickzl** [comment]
好的
