### ISSUE TITLE
开启今日诗词后，如果随机的诗词长度过长在手机浏览下会错位

### ISSUE THREAD

**Issue by ZRdRy** [17px/typecho-theme-shanhai#3]
开启今日诗词后，如果随机的诗词长度过长在手机浏览下会错位

**Comment by 17px** [comment]
> 开启今日诗词后，如果随机的诗词长度过长在手机浏览下会错位

接下来1.0.1版本会解决这个问题 @ZRdRy

**Comment by ZRdRy** [comment]
> > 开启今日诗词后，如果随机的诗词长度过长在手机浏览下会错位
> 
> 接下来1.0.1版本会解决这个问题 @ZRdRy

好的，谢谢作者

**Comment by 17px** [comment]
latest released
