### ISSUE TITLE
切换页面组件报错

### ISSUE THREAD

**Issue by xnov7** [17px/typecho-theme-shanhai#6]
![image](https://github.com/user-attachments/assets/078f5e61-4828-43ac-a437-88cd37cb81c1)

typtcho版本1.2.1，使用的sqlite数据库

**Comment by 17px** [comment]
> ![image](https://private-user-images.githubusercontent.com/42537011/386140729-078f5e61-4828-43ac-a437-88cd37cb81c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2NTY3MDUsIm5iZiI6MTczMTY1NjQwNSwicGF0aCI6Ii80MjUzNzAxMS8zODYxNDA3MjktMDc4ZjVlNjEtNDgyOC00M2FjLWE0MzctODhjZDM3Y2I4MWMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE1VDA3NDAwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxY2I2NDQ1MGIxNDg1NWRlYzZmZWVjZjIwNmEwZDE1NjRmMTgyNTU5ZTNiNDIzZjcxMjQ1NzYyYmFmYzM0M2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.FeFwOv3ljVmQse8sCK1NCmFCwStV6RSD5X04sKEjqsk)
> 
> typtcho版本1.2.1，使用的sqlite数据库

设置>永久链接设置>自定义文章路径中

默认风格、 wordpress风格测试支持的

**Comment by xnov7** [comment]
> > <img alt="image" width="54.145835876464844" height="21" src="https://private-user-images.githubusercontent.com/42537011/386140729-078f5e61-4828-43ac-a437-88cd37cb81c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2NTY3MDUsIm5iZiI6MTczMTY1NjQwNSwicGF0aCI6Ii80MjUzNzAxMS8zODYxNDA3MjktMDc4ZjVlNjEtNDgyOC00M2FjLWE0MzctODhjZDM3Y2I4MWMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE1VDA3NDAwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxY2I2NDQ1MGIxNDg1NWRlYzZmZWVjZjIwNmEwZDE1NjRmMTgyNTU5ZTNiNDIzZjcxMjQ1NzYyYmFmYzM0M2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.FeFwOv3ljVmQse8sCK1NCmFCwStV6RSD5X04sKEjqsk">
> > typtcho版本1.2.1，使用的sqlite数据库
> 
> 设置>永久链接设置>自定义文章路径中
> 
> 默认风格、 wordpress风格测试支持的

重装几次发现问题了，用的PHP8.0，切换成PHP7.2就正常了
